```xml
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- ELEMENTO RAÍZ -->
  <xs:element name="encuestas">

    <xs:complexType>

      <xs:sequence>

        <!-- ENCUESTA -->
        <xs:element name="encuesta" maxOccurs="unbounded">

          <xs:complexType>

            <xs:sequence>

              <!-- USUARIO -->
              <xs:element name="usuario">

                <xs:complexType>

                  <xs:sequence>

                    <xs:element name="tipo">

                      <xs:simpleType>

                        <xs:restriction base="xs:string">

                          <xs:enumeration value="estudiante"/>
                          <xs:enumeration value="profesor"/>
                          <xs:enumeration value="administrativo"/>
                          <xs:enumeration value="otro"/>

                        </xs:restriction>

                      </xs:simpleType>

                    </xs:element>

                    <xs:element name="frecuencia">

                      <xs:simpleType>

                        <xs:restriction base="xs:string">

                          <xs:enumeration value="frecuente"/>
                          <xs:enumeration value="ocasional"/>
                          <xs:enumeration value="rara"/>

                        </xs:restriction>

                      </xs:simpleType>

                    </xs:element>

                  </xs:sequence>

                </xs:complexType>

              </xs:element>

              <!-- ACCESIBILIDAD -->
              <xs:element name="accesibilidad">

                <xs:complexType>

                  <xs:sequence>

                    <xs:element name="contacto">

                      <xs:simpleType>

                        <xs:restriction base="xs:string">

                          <xs:enumeration value="muyfacil"/>
                          <xs:enumeration value="facil"/>
                          <xs:enumeration value="normal"/>
                          <xs:enumeration value="dificil"/>
                          <xs:enumeration value="muydificil"/>

                        </xs:restriction>

                      </xs:simpleType>

                    </xs:element>

                    <xs:element name="canal">

                      <xs:simpleType>

                        <xs:restriction base="xs:string">

                          <xs:enumeration value="presencial"/>
                          <xs:enumeration value="telefono"/>
                          <xs:enumeration value="correo"/>
                          <xs:enumeration value="web"/>
                          <xs:enumeration value="otro"/>

                        </xs:restriction>

                      </xs:simpleType>

                    </xs:element>

                  </xs:sequence>

                </xs:complexType>

              </xs:element>

              <!-- TIEMPO -->
              <xs:element name="tiempo">

                <xs:complexType>

                  <xs:sequence>

                    <xs:element name="espera">

                      <xs:simpleType>

                        <xs:restriction base="xs:string">

                          <xs:enumeration value="muycorto"/>
                          <xs:enumeration value="adecuado"/>
                          <xs:enumeration value="largo"/>
                          <xs:enumeration value="muylargo"/>

                        </xs:restriction>

                      </xs:simpleType>

                    </xs:element>

                    <xs:element name="resolucion">

                      <xs:simpleType>

                        <xs:restriction base="xs:string">

                          <xs:enumeration value="si"/>
                          <xs:enumeration value="no"/>
                          <xs:enumeration value="parcialmente"/>

                        </xs:restriction>

                      </xs:simpleType>

                    </xs:element>

                  </xs:sequence>

                </xs:complexType>

              </xs:element>

              <!-- CALIDAD -->
              <xs:element name="calidad">

                <xs:complexType>

                  <xs:sequence>

                    <xs:element name="trato">

                      <xs:simpleType>

                        <xs:restriction base="xs:string">

                          <xs:enumeration value="excelente"/>
                          <xs:enumeration value="bueno"/>
                          <xs:enumeration value="regular"/>
                          <xs:enumeration value="malo"/>

                        </xs:restriction>

                      </xs:simpleType>

                    </xs:element>

                    <xs:element name="ayuda">

                      <xs:simpleType>

                        <xs:restriction base="xs:string">

                          <xs:enumeration value="siempre"/>
                          <xs:enumeration value="casisiempre"/>
                          <xs:enumeration value="aveces"/>
                          <xs:enumeration value="nunca"/>

                        </xs:restriction>

                      </xs:simpleType>

                    </xs:element>

                    <xs:element name="claridad">

                      <xs:simpleType>

                        <xs:restriction base="xs:string">

                          <xs:enumeration value="muyclara"/>
                          <xs:enumeration value="clara"/>
                          <xs:enumeration value="pococlara"/>
                          <xs:enumeration value="nadaclara"/>

                        </xs:restriction>

                      </xs:simpleType>

                    </xs:element>

                  </xs:sequence>

                </xs:complexType>

              </xs:element>

              <!-- VALORACIÓN -->
              <xs:element name="valoracion">

                <xs:complexType>

                  <xs:sequence>

                    <xs:element name="problema">

                      <xs:simpleType>

                        <xs:restriction base="xs:string">

                          <xs:enumeration value="completo"/>
                          <xs:enumeration value="parcial"/>
                          <xs:enumeration value="no"/>

                        </xs:restriction>

                      </xs:simpleType>

                    </xs:element>

                    <xs:element name="general">

                      <xs:simpleType>

                        <xs:restriction base="xs:string">

                          <xs:enumeration value="excelente"/>
                          <xs:enumeration value="bueno"/>
                          <xs:enumeration value="regular"/>
                          <xs:enumeration value="malo"/>

                        </xs:restriction>

                      </xs:simpleType>

                    </xs:element>

                    <xs:element name="recomendacion">

                      <xs:simpleType>

                        <xs:restriction base="xs:string">

                          <xs:enumeration value="si"/>
                          <xs:enumeration value="no"/>

                        </xs:restriction>

                      </xs:simpleType>

                    </xs:element>

                    <xs:element name="puntuacion">

                      <xs:simpleType>

                        <xs:restriction base="xs:integer">

                          <xs:minInclusive value="1"/>
                          <xs:maxInclusive value="5"/>

                        </xs:restriction>

                      </xs:simpleType>

                    </xs:element>

                    <xs:element name="sentimiento">

                      <xs:simpleType>

                        <xs:restriction base="xs:string">

                          <xs:enumeration value="muyinsatisfecho"/>
                          <xs:enumeration value="insatisfecho"/>
                          <xs:enumeration value="neutral"/>
                          <xs:enumeration value="satisfecho"/>
                          <xs:enumeration value="muysatisfecho"/>

                        </xs:restriction>

                      </xs:simpleType>

                    </xs:element>

                  </xs:sequence>

                </xs:complexType>

              </xs:element>

            </xs:sequence>

            <!-- ATRIBUTO ID -->
            <xs:attribute 
              name="id" 
              type="xs:integer" 
              use="required"
            />

          </xs:complexType>

        </xs:element>

      </xs:sequence>

    </xs:complexType>

  </xs:element>

</xs:schema>
```
